!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  P1: 200.0
  P2: 400.0
  correlation_window_size: 13
  disp12MaxDiff: 0
  disparity_range: 48
  fullDP: false
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      P1: 200.0
      P2: 400.0
      correlation_window_size: 13
      disp12MaxDiff: 0
      disparity_range: 48
      fullDP: false
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      min_disparity: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      prefilter_cap: 29
      prefilter_size: 9
      speckle_range: 1
      speckle_size: 64
      state: true
      stereo_algorithm: 0
      texture_threshold: 864
      type: ''
      uniqueness_ratio: 51.0
    state: []
  min_disparity: 0
  prefilter_cap: 29
  prefilter_size: 9
  speckle_range: 1
  speckle_size: 64
  stereo_algorithm: 0
  texture_threshold: 864
  uniqueness_ratio: 51.0
state: []
