pipelines:
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - parallel:
        - step:
            image: osrf/vrx:current
            script:
              # Code style
              - sudo apt-get -y install cppcheck protobuf-compiler
              - sh tools/code_check.sh
              # Set up workspace
              - mkdir -p /tmp/vrx_ws/src
              - ln -s `pwd` /tmp/vrx_ws/src
              - cd /tmp/vrx_ws
              # Build and run tests.
              - source /opt/ros/melodic/setup.bash
              - catkin_make -j1
              - catkin_make run_tests -j1
        - step:
            image: osrf/vrx:test_gaz7
            script:
              # Code style
              - sudo apt-get -y install cppcheck protobuf-compiler
              - sh tools/code_check.sh
              # Set up workspace
              - mkdir -p /tmp/vrx_ws/src
              - ln -s `pwd` /tmp/vrx_ws/src
              - cd /tmp/vrx_ws
              # Build and run tests.
              - source /opt/ros/kinetic/setup.bash
              - catkin_make -j1
              - catkin_make run_tests -j1
